name: Build EXE with PyInstaller

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Descargar el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # Instalar Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Instalar dependencias
      - name: Install dependencies
        run: |
          pip install pandas openpyxl pyinstaller

      # Compilar main.py
      - name: Build MAIN
        run: |
          pyinstaller --onefile main.py

      # Compilar WORD.py
      - name: Build WORD
        run: |
          pyinstaller --onefile WORD.py

      # Compilar VENTAS.py
      - name: Build VENTAS
        run: |
          pyinstaller --onefile VENTAS.py

      # Subir los ejecutables generados
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Ejecutables
          path: |
            dist/main.exe
            dist/WORD.exe
            dist/VENTAS.exe
